//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется FXGraph.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MENU_LINK                   101
#define IDS_TOOLBAR_PROJECT             102
#define ID_INDICATOR_COORD              103
#define ID_INDICATOR_TICKS              104
#define IDS_GRAPH_VIEW                  105
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_TOOLBAR_GRID                126
#define IDS_TOOLBAR_ALIGN               127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_FXGraphTYPE                 130
#define ID_WINDOW_MANAGER               131
#define IDS_TOOLBAR_DEBUG               132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_MENU_BLOCK                  307
#define IDS_MENU_PIN                    308
#define IDR_TOOLBAR_GRID                310
#define IDD_GRID                        312
#define ID_VIEW_GRAPHVIEW               312
#define IDR_TOOLBAR_ALIGN               314
#define IDR_BLOCK                       319
#define IDR_PIN                         320
#define IDR_LINK                        321
#define IDD_COMMENT                     322
#define IDR_TOOLBAR_DEBUG               324
#define IDR_TOOLBAR_PROJECT             325
#define IDD_PARAM                       331
#define IDD_PROJECT                     333
#define IDR_CLASSMENU                   335
#define IDD_FINDID                      336
#define IDR_GRAPHMENU                   342
#define IDD_GRAPH                       343
#define IDR_GRAPHPINMENU                346
#define IDD_GRAPHPIN                    347
#define IDI_ICON1                       352
#define IDI_GRAPH_VIEW_HC               352
#define IDC_GRID_ONOFF                  1000
#define IDC_RADIO2                      1001
#define IDC_GRID_STYLE_POINTS           1002
#define IDC_GRID_STYLE_LINES            1003
#define IDC_STEP                        1005
#define IDC_GRID_BIND                   1006
#define IDC_MFCCOLORBUTTON1             1007
#define IDC_COLOR                       1007
#define IDC_COMMENT                     1008
#define IDC_EDIT1                       1010
#define IDC_COMBO1                      1011
#define IDC_RADIO1                      1012
#define IDC_EDIT2                       1013
#define IDC_EDIT3                       1014
#define IDC_CYCLE_TICKS                 1015
#define IDC_TIMER                       1016
#define ID_GRID                         32771
#define ID_ALIGN_RIGHT                  32772
#define ID_ALIGN_TOP                    32773
#define ID_ALIGN_BOTTOM                 32774
#define ID_ALIGN_LEFT                   32775
#define ID_BLOCK_INPUTPIN_ADD_LOGICAL   32792
#define ID_BLOCK_INPUTPIN_ADD_INT       32793
#define ID_BLOCK_INPUTPIN_ADD_FLOAT     32794
#define ID_BLOCK_OUTPUTPIN_ADD_LOGICAL  32795
#define ID_BLOCK_OUTPUTPIN_ADD_INT      32796
#define ID_BLOCK_OUTPUTPIN_ADD_FLOAT    32797
#define ID_PIN_REMOVE                   32798
#define ID_PIN_                         32799
#define ID_BLOCK_PIN_REMOVE             32800
#define ID_SHOW_LINKS                   32803
#define ID_LINK_REMOVE                  32805
#define ID_BLOCK_REMOVE                 32806
#define ID_DEBUG_START                  32809
#define ID_DEBUG_RESTART                32810
#define ID_DEBUG_STEP                   32811
#define ID_DEBUG_STOP                   32813
#define ID_PARAMS                       32814
#define ID_INPUT_PARAM_ADD              32815
#define ID_PARAM_OUTPUT_ADD             32816
#define ID_PARAM_REMOVE                 32817
#define ID_PARAM_INPUT_ADD              32818
#define ID_DEBUG_STEP_INTO              32819
#define ID_DEBUG_STEP_OVER              32820
#define ID_DEBUG_STEP_TO                32821
#define ID_FINDBYID                     32822
#define ID_PROJECT_PROPERTIES           32823
#define ID_CLASSVIEWMENU_WEB            32824
#define ID_CLASSVIEWMENU_WEBHELP        32825
#define ID_BLOCK_WEBHELP                32827
#define ID_BLOCK_BREAKPOINT             32829
#define ID_Menu                         32830
#define ID_BLOCK_PIN_REMOVE_LINKS       32831
#define ID_DEBUG_PAUSE                  32832
#define ID_PROJECT_SCENARIO             32833
#define ID_PIN_GRAPH                    32836
#define ID_PIN_GRAPH_NEW                32842
#define ID_PROJECT_GRAPHS               32843
#define ID_ASD_32844                    32844
#define ID_ASD_32845                    32845
#define ID_GRAPH_ADD                    32846
#define ID_GRAPH_REMOVE                 32847
#define ID_GRAPHVIEWMENU_32848          32848
#define ID_GRAPH_RENAME                 32849
#define ID_GRAPHVIEWMENU_32850          32850
#define ID_GRAPH_OPEN                   32851
#define ID_IDR_32852                    32852
#define ID_IDR_32853                    32853
#define ID_IDR_32854                    32854
#define ID_GRAPH_PIN                    32855
#define ID_GRAPH_PIN_REMOVE             32856
#define ID_GRAPH_PIN_PROPERTIES         32857
#define ID_BUTTON32858                  32858
#define ID_PROJECT_TOP                  32858

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32859
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
